#Sonar organization (required)
sonar.organization=pablo-martinez-anorga
#sonar project Key (required)
sonar.projectKey=pablo-martinez-anorga_market26
#Sonar projectName. The name that appears on a Sonar
dashboard (required)
sonar.projectName=Market26
#Maven version. (required)
sonar.projectVersion=0.0.1
#Path with java code (required)
#Helbide erlatiboa
sonar.sources=src
sonar.test=src/test/java
#All paths that contain test (optional)
tests=src
#Paths where the binaries of the project are located
(required)
binaries=bin
sonar.java.binaries=bin
# The project languaje (java for defect)
sonar.language=java
sonar.host.url=https://sonarcloud.io
sonar.dynamicAnalysis=reuseReports
sonar.exclusions=src/test/**,**/AñadirSaldo.java